/**
 * 
 * URL which will be used for API calling should be declared in this file.
 */

export const AppInfo = {
    // baseUrlAPI: 'https://cigapi.affleprojects.com',
    // apiVersion: 'v1',
    // serviceTimeOut: 20000,
    // baseUrlAPI: 'http://fundauat.affleprojects.com', :- Uat Server
    // baseUrlAPI: 'http://35.247.132.150:3008',       :- Dev Server

    baseUrlAPI: 'http://35.247.132.150:3008',
    // baseUrlAPI: 'http://fundauat.affleprojects.com',
    apiVersion: 'v1',
    serviceTimeOut: 20000,
};

export default {
    getRequest: 'GET',
    postRequest: 'POST',
    deleteRequest: 'DELETE',
    putRequest: 'PUT',
    baseURL: AppInfo.baseUrlAPI + "/" + AppInfo.apiVersion + "/",

    dummy_api: '/web/getTnC',
    verifyOtp: 'common/verifyOTP',
    countryCode: 'common/getCountryCode',
    login: 'common/login',
    socialMediaLogin: 'common/socialMediaLogin',
    updateStudent: 'student/updateStudent',
    updateTutor: 'tutor/updateTutor',
    getEducationDetails: 'common/getEducationDetails',
    bookSession: 'student/bookSession',
    cancelSession: 'student/cancelSession',
    customerQuery: 'common/customerQuery',
    bookSession: 'student/bookSession',
    rescheduleSession: 'student/rescheduleSession',
    tutorRescheduleSession: 'tutor/rescheduleTutorSession',
    homeScreen: 'student/getSessionsHome',
    sessionDetail: 'student/getSessionDetail',
    getSessions: 'student/getSessions',
    startSession: 'student/startSession',
    bidList: 'student/getBidsList',
    rateTutor: 'tutor/rateTutor',
    getBiddingPrice: 'tutor​/getBiddingPrice',
    updateBid: 'student/updateBid',
    getPages: 'common/getPages',
    getTutorList: 'student/myTutorListing',
    getTutorHome: "tutor/getTutorSessionsHome",
    rateTutor: 'tutor/rateTutor',
    getBiddingPrice: 'tutor​/getBiddingPrice',
    getTutorSubjects: 'tutor/getTutorSubjects',
    newlyAddedSession: 'tutor/newlyAddedSession',
    tutorFilterSession: 'tutor/filterSession',
    studentGetSubjects: 'student/getStudentSubjects',
    getStudentSessions: 'student/getMySessions',
    rateTutor: 'tutor/rateTutor',
    getTutorHome: 'tutor/getTutorSessionsHome',
    placeBid: 'tutor/placeBid',
    tutorManageSession: 'tutor/manageSession',
    getAllScheduledSessions: 'tutor/getAllScheduledSession',
    newlyAddedSessionDetail: 'tutor/getnewlyAddedSessionDetail',
    getTutorSessionDetail: 'tutor/getTutorSessionDetail',
    tutoFilterSession: 'tutor/filterSession',
    getAllTutorSubjects: 'tutor/getTutorSubjects',
    filterNewlyAddedSession: 'tutor/filterNewlySession',
    getStudentSessions: 'student/getMySessions',
    tutorRescheduleSession: 'tutor/rescheduleTutorSession',
    videoCallSessionStart: 'common/createSessionAndSendNotification',
    cancelTutorSession: 'tutor/cancelTutorSession',
    verifyRefferalCode: 'student/verifyReferralID',
    verifyTutorReferal: 'tutor/verifyTutorReferralID',
    completeSession: 'common/completeSession',
    rateTutor: 'tutor/rateTutor',
    raiseDisputeStudent: 'student/raiseDesputeStudent',
    rateStudent: 'student/rateStudent',
    getTutorProfile: 'student/getTutorProfile',
    getDisputeList: 'common/getDisputeList',
    raiseDisputeTutor: 'tutor/raiseDesputeTutor',
    tutorVerifyCharges: 'tutor/tutorVerifyCharges',
    studentVerifyCharges: 'student/studentVerifyCharges',
    myClass: 'student/myClasses',
    logout: 'common/logout',
    checkPreviousSessionRated: 'student/checkPreviousSessionRatedS',
    checkPreviousSessionRatedTutor: 'tutor/checkPreviousSessionRated',
    listNotifications: 'common/notificationList',
    readNotification: 'common/updateNotification',
    appleLogin: 'common/appleLogin'
}
