
export const API_CALL = 'API_CALL';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const DUMMY_API_CALL = 'DUMMY_API_CALL';

export const COUNTRY_CODE_API = 'COUNTRY_CODE_API';
export const LOGIN_API_CALL = 'LOGIN_API_CALL';
export const EDUCATION_DETAIL_API_CALL = 'EDUCATION_DETAIL_API_CALL';

// Notification Action Types
export const CHANGE_NOTIFICATION_BELL_ICON = 'CHANGE_NOTIFICATION_BELL_ICON';
export const KILLED_STATE_NOTIFICATION_DATA = 'KILLED_STATE_NOTIFICATION_DATA';